# Generated by Django 4.2.4 on 2023-09-19 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_comment_options_recipe_recipe_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='image_url',
            field=models.CharField(blank=True, default='/static/images/hard_coded_image.jpg', max_length=500),
        ),
    ]
