# Generated by Django 4.2.4 on 2023-09-19 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_recipe_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='is_hardcoded',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='image_url',
            field=models.CharField(blank=True, default='/media/images/creamy-tomato-soup-buttery-croutons-hero-02-49b419d00f854db78838a79c8df9a23f.jpg', max_length=500),
        ),
    ]
